//
// Created by Pd on 7/6/26.
//

#ifndef RAYLIB_GAME_TEMPLATE_ENUMS_H
#define RAYLIB_GAME_TEMPLATE_ENUMS_H

enum class GameScreen {
    SCREEN_BOOK,
    SCREEN_SHOP,
    SCREEN_WORKSHOP,
    SCREEN_MARKET
};

#endif //RAYLIB_GAME_TEMPLATE_ENUMS_H